name: test first github action

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

  name: run start function
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3

    - run: python main.py

