name: test first github action

on:
  push:
    branches: [ "main" ]
jobs:
  name: run container and print this_works

  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    - run: python main.py

